name: PHP Composer

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Initialize Composer
      run: composer init --name="my/app"

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install OpenAI
      run: composer require openai-php/client
      
    - name: Install Guzzle
      run: composer require guzzlehttp/guzzle
      
    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
        unzip ngrok-v3-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      
    - name: Start ngrok
      run: ./ngrok http 80

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
